import { Roboto } from "next/font/google";
import "aos/dist/aos.css";
import "react-medium-image-zoom/dist/styles.css";
import "react-quill/dist/quill.snow.css";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
